In [27]:
import mlrose_hiive as mlrose
import numpy as np
import pandas as pd

In [28]:
# Create list of city coordinates
coords_list = [(1, 1), (4, 2), (5, 2), (6, 4), (4, 4), (3, 6), (1, 5), (2, 3)]

# Initialize fitness function object using coords_list
fitness_coords = mlrose.TravellingSales(coords = coords_list)

In [3]:
# Create list of distances between pairs of cities
dist_list = [(0, 1, 3.1623), (0, 2, 4.1231), (0, 3, 5.8310), (0, 4, 4.2426), \
             (0, 5, 5.3852), (0, 6, 4.0000), (0, 7, 2.2361), (1, 2, 1.0000), \
             (1, 3, 2.8284), (1, 4, 2.0000), (1, 5, 4.1231), (1, 6, 4.2426), \
             (1, 7, 2.2361), (2, 3, 2.2361), (2, 4, 2.2361), (2, 5, 4.4721), \
             (2, 6, 5.0000), (2, 7, 3.1623), (3, 4, 2.0000), (3, 5, 3.6056), \
             (3, 6, 5.0990), (3, 7, 4.1231), (4, 5, 2.2361), (4, 6, 3.1623), \
             (4, 7, 2.2361), (5, 6, 2.2361), (5, 7, 3.1623), (6, 7, 2.2361)]

# Initialize fitness function object using dist_list
fitness_dists = mlrose.TravellingSales(distances = dist_list)

In [20]:
# Define optimization problem object
problem_fit = mlrose.TSPOpt(length = 8, fitness_fn = fitness_dists, maximize=False)
problem_name = "TravellingSales_Problem"
output_dir = "TravellingSales"
random_state = 2024


In [11]:
# Solve problem using the genetic algorithm
best_state, best_fitness , curve = mlrose.genetic_alg(problem_fit, random_state = 2)

print(best_state)

print(best_fitness)


[7 6 5 4 3 2 1 0]
17.3428


In [12]:
# Solve problem using the genetic algorithm
best_state, best_fitness , gcurve = mlrose.genetic_alg(problem_fit, mutation_prob = 0.2,
                                              max_attempts = 100, random_state = 2)

print(best_state)

print(best_fitness)

[1 0 7 6 5 4 3 2]
17.3428


In [19]:

schedule = mlrose.ExpDecay()
best_state, best_fitness , sacurve = mlrose.simulated_annealing(problem_fit, schedule = schedule,max_attempts = 10000, max_iters = 1000, random_state = 1)
print(best_state)

print(best_fitness)


[4 3 2 1 0 7 6 5]
17.3428


In [21]:
mim = mlrose.MIMICRunner(problem=problem_fit,
                       experiment_name=problem_name,
                       output_directory=output_dir,
                       seed=random_state,
                       population_sizes=[50, 100, 200, 500, 1000, 2000],
                       keep_percent_list=[0.1, 0.25, 0.5, 0.7, 0.8],
                       iteration_list=[50],
                       use_fast_mimic=True)
mim_stats, mim_curve = mim.run()

In [24]:
show=10
columns = ['Time', 'Fitness', 'Population Size', 'Keep Percent']
pd.set_option('display.max_rows',show)
df=pd.read_csv("./TravellingSales/TravellingSales_Problem/mimic__TravellingSales_Problem__run_stats_df.csv")
df[columns].sort_values(by=['Fitness'], ascending=True).head(show)

Time  Fitness  Population Size  Keep Percent
59  7.548991  17.3428             2000          0.80
31  1.872823  17.3428              500          0.10
33  1.850801  17.3428              500          0.25
13  0.379532  17.3428              100          0.25
35  2.618223  17.3428              500          0.50
37  2.443010  17.3428              500          0.70
39  3.005654  17.3428              500          0.80
25  0.832298  17.3428              200          0.50
41  3.549965  17.3428             1000          0.10
45  3.638015  17.3428             1000          0.50